FROM --platform=linux debian:latest
ARG BUILDARCH

ENV LOCAL=/usr/local

COPY build/cosmos-checkersd-linux-${BUILDARCH} ${LOCAL}/bin/cosmos-checkersd

RUN cosmos-checkersd init cosmos-checkers --chain-id "cosmos-checkers-1"

RUN chmod -R 777 /root/.cosmos-checkers/config
RUN chmod -R 777 /root/.cosmos-checkers/data

RUN sed -i 's/"stake"/"upawn"/g' /root/.cosmos-checkers/config/genesis.json
RUN sed -Ei 's/([0-9]+)stake/\1upawn/g' /root/.cosmos-checkers/config/app.toml
RUN sed -Ei 's/^chain-id = .*$/chain-id = "cosmos-checkers-1"/g' /root/.cosmos-checkers/config/client.toml