FROM --platform=linux rust:1.64.0 AS builder

RUN apt-get update
RUN apt-get install libusb-1.0-0-dev --yes

ENV LOCAL=/usr/local
ENV RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
ENV TMKMS_VERSION=v0.12.2

WORKDIR /root
RUN git clone --branch ${TMKMS_VERSION} https://github.com/iqlusioninc/tmkms.git
WORKDIR /root/tmkms
RUN cargo build --release --features=softsign

# The production image starts here
FROM --platform=linux debian:latest

COPY --from=builder /root/tmkms/target/release/tmkms ${LOCAL}/bin

RUN tmkms init /root/tmkms 
RUN sed -Ei 's/^protocol_version = .*$/protocol_version = "v0.34"/g' \
    /root/tmkms/tmkms.toml
RUN sed -Ei 's/path = "\/root\/tmkms\/secrets\/cosmoshub-3-consensus.key"/path = "\/root\/tmkms\/secrets\/val-alice-consensus.key"/g' \
    /root/tmkms/tmkms.toml
RUN sed -Ei 's/cosmoshub-3/cosmos-checkers-1/g' /root/tmkms/tmkms.toml