# This Dockerfile will: 
# set up a Golang environment(using Golang Docker Image)
# install Ignite
# use the checkers game repository
# with the leaderboard included
# start a checkers blockchain
# expose api endpoints

# Use Golang Docker Image
FROM golang:1.18

# Set working dir
WORKDIR /home/cosmoscheckers

# Install tools
RUN apt-get install curl git

# Install ignite
RUN curl -L https://get.ignite.com/cli@v0.22.1! | bash

# Copy local repository
ADD cosmos-checkers-app /home/cosmoscheckers

# Copy Test
COPY ./test.sh /home/cosmoscheckers
RUN chmod +x ./test.sh

# Copy serve script
COPY ./run-checkers.sh /home/cosmoscheckers
RUN chmod +x ./run-checkers.sh

ENTRYPOINT ["/bin/bash", "-c", "/home/cosmoscheckers/run-checkers.sh"]
EXPOSE 26657 1317 4500